In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [2]:
arr = np.array([
    [7, 8, 9],
    [10, 11, 12]
])
print(arr)

[[ 7  8  9]
 [10 11 12]]


In [4]:
#Task: Create 3×3 matrix and print shape, size, dimensions
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr.shape)
print(arr.size)
print(arr.ndim)

(3, 3)
9
2


In [5]:
print(np.zeros((4, 4)))
print(np.ones((2, 5)))
print(np.eye(5))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [6]:
print(np.arange(1, 21))
print(np.arange(2, 21, 2))
print(np.arange(5, 51, 5))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]
[ 5 10 15 20 25 30 35 40 45 50]


In [7]:
arr1 = np.arange(1, 11).reshape(2, 5)
print(arr1)

arr2 = np.arange(1, 13).reshape(4, 3)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
arr = np.array([10, 20, 30, 40, 50])
print("First:", arr[0])
print("Last:", arr[-1])
print("Middle:", arr[len(arr) // 2])

First: 10
Last: 50
Middle: 30


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("First 3:", arr[:3])
print("Last 2:", arr[-2:])
print("Alternate:", arr[::2])

First 3: [1 2 3]
Last 2: [5 6]
Alternate: [1 3 5]


In [10]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr[0, 1])       # 20
print(arr[1, 2])       # 60
print(arr[0, :])       # first row
print(arr[:, 1])       # second column

20
60
[10 20 30]
[20 50]


In [11]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print("Add:", a + b)
print("Subtract:", a - b)
print("Multiply:", a * b)
print("Divide:", a / b)

Add: [11 22 33]
Subtract: [ 9 18 27]
Multiply: [10 40 90]
Divide: [10. 10. 10.]


In [12]:
arr = np.array([5, 10, 15, 20, 25])
print("Sum:", np.sum(arr))
print("Average:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

Sum: 75
Average: 15.0
Maximum: 25
Minimum: 5
