In [11]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [2]:
arr = np.array([
    [7, 8, 9],
    [10, 11, 12]
])
print(arr)

[[ 7  8  9]
 [10 11 12]]


In [4]:
#Task: Create 3×3 matrix and print shape, size, dimensions
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr.shape)
print(arr.size)
print(arr.ndim)

(3, 3)
9
2


In [5]:
print(np.zeros((4, 4)))
print(np.ones((2, 5)))
print(np.eye(5))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [6]:
print(np.arange(1, 21))
print(np.arange(2, 21, 2))
print(np.arange(5, 51, 5))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]
[ 5 10 15 20 25 30 35 40 45 50]


In [7]:
arr1 = np.arange(1, 11).reshape(2, 5)
print(arr1)

arr2 = np.arange(1, 13).reshape(4, 3)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
arr = np.array([10, 20, 30, 40, 50])
print("First:", arr[0])
print("Last:", arr[-1])
print("Middle:", arr[len(arr) // 2])

First: 10
Last: 50
Middle: 30


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("First 3:", arr[:3])
print("Last 2:", arr[-2:])
print("Alternate:", arr[::2])

First 3: [1 2 3]
Last 2: [5 6]
Alternate: [1 3 5]


In [10]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr[0, 1])       # 20
print(arr[1, 2])       # 60
print(arr[0, :])       # first row
print(arr[:, 1])       # second column

20
60
[10 20 30]
[20 50]


In [11]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print("Add:", a + b)
print("Subtract:", a - b)
print("Multiply:", a * b)
print("Divide:", a / b)

Add: [11 22 33]
Subtract: [ 9 18 27]
Multiply: [10 40 90]
Divide: [10. 10. 10.]


In [12]:
arr = np.array([5, 10, 15, 20, 25])
print("Sum:", np.sum(arr))
print("Average:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

Sum: 75
Average: 15.0
Maximum: 25
Minimum: 5


In [13]:
print(np.random.randint(1, 100, 10))
print(np.random.randint(1, 100, (3, 3)))
print(np.random.randint(50, 101, 5))

[26 25 78 88 67 30 24 12 35 22]
[[27 31 70]
 [11 14 34]
 [65 11 50]]
[67 94 88 55 85]


In [14]:
#Task: Numbers greater than 50, and even numbers only
arr = np.array([10, 35, 55, 72, 20, 88, 43, 61])
print("Greater than 50:", arr[arr > 50])
print("Even numbers:", arr[arr % 2 == 0])

Greater than 50: [55 72 88 61]
Even numbers: [10 72 20 88]


In [15]:
#Task: Add 5 and 100 to all elements
arr = np.array([1, 2, 3, 4, 5])
print("Add 5:", arr + 5)
print("Add 100:", arr + 100)

Add 5: [ 6  7  8  9 10]
Add 100: [101 102 103 104 105]


In [16]:
#Task: 10 students — total, average, highest, lowest, failed (<35)
marks = np.array([78, 85, 90, 32, 56, 
                  43, 29, 67, 88, 71])

print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Failed students (marks < 35):", marks[marks < 35])

Total: 639
Average: 63.9
Highest: 90
Lowest: 29
Failed students (marks < 35): [32 29]


In [17]:
#Create a multiplication table using NumPy
table = np.arange(1, 11).reshape(10, 1) * np.arange(1, 11)
print(table)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [18]:
#Create a 5×5 matrix from numbers 1 to 25
arr = np.arange(1, 26).reshape(5, 5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])


[2 3 4 5]


In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [3]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])


[5 6]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])


[2 4]


In [5]:
a = np.arange(0, 10)

print('a=', a)
print('a[2:5]=', a[2:5])
print('a[:]=', a[:])
print('a[0:-1]=', a[0:-1])
print('a[0:6]=', a[0:6])
print('a[7:]=', a[7:])
print('a[5:-1]=', a[5:-1])
print('a[0:5:2]=', a[0:5:2])
print('a[::-1]=', a[::-1])


a= [0 1 2 3 4 5 6 7 8 9]
a[2:5]= [2 3 4]
a[:]= [0 1 2 3 4 5 6 7 8 9]
a[0:-1]= [0 1 2 3 4 5 6 7 8]
a[0:6]= [0 1 2 3 4 5]
a[7:]= [7 8 9]
a[5:-1]= [5 6 7 8]
a[0:5:2]= [0 2 4]
a[::-1]= [9 8 7 6 5 4 3 2 1 0]


In [10]:
numbers = [5, 2, 9, 1]
numbers.sort()
print(numbers)  # [1, 2, 5, 9]
numbers.reverse()
print(numbers)  

[1, 2, 5, 9]
[9, 5, 2, 1]


In [12]:
for i in range(10, 0, -1):
    print(i)


10
9
8
7
6
5
4
3
2
1


In [13]:
for i in range(10, 5, -1):
    print(i)


10
9
8
7
6


In [14]:
r = range(1, 10, 2)
print(list(r))


[1, 3, 5, 7, 9]


In [15]:
r = range(1, 10, 1)
print(list(r))


[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [17]:
r = range(1, 10, 3)
print(list(r))


[1, 4, 7]


In [18]:
phonebook = {"Alice": "9876543210", "Bob": "9123456789"}
print("Bob's number:", phonebook["Bob"])


Bob's number: 9123456789


In [19]:
visitors = {"Alice", "Bob", "Alice"}  
print(visitors)

{'Alice', 'Bob'}


In [23]:
class MyClass:
      x = 5
      y=7

p1 = MyClass()
print(p1.y)
print(p1.x)


7
5


In [26]:
a = ["10", "twenty", 30] # Mixed list of integers and strings
try:
    total = int(a[0]) + int(a[1]) # 'twenty' cannot be converted to int
except (ValueError, TypeError) as e:
    print("Error", e)
except IndexError:
    print("Index out of range.")

Error invalid literal for int() with base 10: 'twenty'


In [3]:

import pandas as pd

marks  = pd.Series([80, 85, 90, 75, 95], index=['Math', 'Science', 'English', 'History', 'Art'])
print(marks)




Math       80
Science    85
English    90
History    75
Art        95
dtype: int64


In [4]:
import pandas as pd
import numpy as np
#create a numpy array of shape (3, 4)
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print(arr)  

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
df=pd.DataFrame(arr, columns=['A', 'B', 'C', 'D'])
print(df)

   A   B   C   D
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12


In [6]:
data={"name":["Alice", "Bob", "Charlie"],
      "age":[25, 30, 35],
      "city":["New York", "Los Angeles", "Chicago"]}
df=pd.DataFrame(data)
print(df)

      name  age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [7]:
print(df.iloc[2,1])  # Accessing the age of the third person (Charlie)

35


In [8]:
print(df.iloc[0:2])

    name  age         city
0  Alice   25     New York
1    Bob   30  Los Angeles


In [9]:
print(df.iloc[:,2])

0       New York
1    Los Angeles
2        Chicago
Name: city, dtype: str


In [10]:
print(df.iloc[:,1])

0    25
1    30
2    35
Name: age, dtype: int64


In [12]:
print(df.iloc[1:3])

      name  age         city
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [13]:
print(df.iloc[:,:-1])

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35


In [14]:
print(df.iloc[:,-1])

0       New York
1    Los Angeles
2        Chicago
Name: city, dtype: str


In [15]:
new_series = pd.Series([10, 20, 30, 40, 50])
print(new_series)
print(new_series[2])  # Accessing the third element (30)

0    10
1    20
2    30
3    40
4    50
dtype: int64
30


In [16]:
print(new_series.values)  # Accessing the underlying numpy array

[10 20 30 40 50]


In [17]:
#show dot product of two series
series1 = pd.Series([1, 2, 3])
series2 = pd.Series([4, 5, 6])
dot_product = series1.dot(series2)
print("Dot Product:", dot_product)

Dot Product: 32


In [18]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = np.dot(A, B)

print(C)

[[19 22]
 [43 50]]


In [19]:
# Create an array of zeros
zeros = np.zeros((3, 3))
print("Zeros Array:\n", zeros)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
import numpy as np

# Create an array of zeros
zeros = np.zeros((3, 3))
print("Zeros Array:\n", zeros)

# Create an array of ones
ones = np.ones((2, 4))
print("\nOnes Array:\n", ones)

# Generate numbers from 1 to 20
arr = np.arange(1, 21)
print("\nArray:", arr)

# Find maximum element
print("Maximum:", np.max(arr))

# Find minimum element
print("Minimum:", np.min(arr))

# Calculate mean
print("Mean:", np.mean(arr))

# Calculate standard deviation
print("Standard Deviation:", np.std(arr))

# Reshape the array
reshaped = arr.reshape(4, 5)
print("\nReshaped Array:\n", reshaped)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Maximum: 20
Minimum: 1
Mean: 10.5
Standard Deviation: 5.766281297335398

Reshaped Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [23]:

from scipy import stats


data = [2, 4, 4, 6, 8]

# Mean
print("Mean:", np.mean(data))

# Median
print("Median:", np.median(data))

# Mode  
print("Mode:", stats.mode(data, keepdims=True))

Mean: 4.8
Median: 4.0
Mode: ModeResult(mode=array([4]), count=array([2]))
