In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [2]:
arr = np.array([
    [7, 8, 9],
    [10, 11, 12]
])
print(arr)

[[ 7  8  9]
 [10 11 12]]


In [4]:
#Task: Create 3×3 matrix and print shape, size, dimensions
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr.shape)
print(arr.size)
print(arr.ndim)

(3, 3)
9
2


In [5]:
print(np.zeros((4, 4)))
print(np.ones((2, 5)))
print(np.eye(5))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [6]:
print(np.arange(1, 21))
print(np.arange(2, 21, 2))
print(np.arange(5, 51, 5))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]
[ 5 10 15 20 25 30 35 40 45 50]
