In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [2]:
arr = np.array([
    [7, 8, 9],
    [10, 11, 12]
])
print(arr)

[[ 7  8  9]
 [10 11 12]]


In [4]:
#Task: Create 3×3 matrix and print shape, size, dimensions
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr.shape)
print(arr.size)
print(arr.ndim)

(3, 3)
9
2


In [5]:
print(np.zeros((4, 4)))
print(np.ones((2, 5)))
print(np.eye(5))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [6]:
print(np.arange(1, 21))
print(np.arange(2, 21, 2))
print(np.arange(5, 51, 5))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]
[ 5 10 15 20 25 30 35 40 45 50]


In [7]:
arr1 = np.arange(1, 11).reshape(2, 5)
print(arr1)

arr2 = np.arange(1, 13).reshape(4, 3)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
arr = np.array([10, 20, 30, 40, 50])
print("First:", arr[0])
print("Last:", arr[-1])
print("Middle:", arr[len(arr) // 2])

First: 10
Last: 50
Middle: 30


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("First 3:", arr[:3])
print("Last 2:", arr[-2:])
print("Alternate:", arr[::2])

First 3: [1 2 3]
Last 2: [5 6]
Alternate: [1 3 5]


In [10]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr[0, 1])       # 20
print(arr[1, 2])       # 60
print(arr[0, :])       # first row
print(arr[:, 1])       # second column

20
60
[10 20 30]
[20 50]


In [11]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print("Add:", a + b)
print("Subtract:", a - b)
print("Multiply:", a * b)
print("Divide:", a / b)

Add: [11 22 33]
Subtract: [ 9 18 27]
Multiply: [10 40 90]
Divide: [10. 10. 10.]


In [12]:
arr = np.array([5, 10, 15, 20, 25])
print("Sum:", np.sum(arr))
print("Average:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

Sum: 75
Average: 15.0
Maximum: 25
Minimum: 5


In [13]:
print(np.random.randint(1, 100, 10))
print(np.random.randint(1, 100, (3, 3)))
print(np.random.randint(50, 101, 5))

[26 25 78 88 67 30 24 12 35 22]
[[27 31 70]
 [11 14 34]
 [65 11 50]]
[67 94 88 55 85]


In [14]:
#Task: Numbers greater than 50, and even numbers only
arr = np.array([10, 35, 55, 72, 20, 88, 43, 61])
print("Greater than 50:", arr[arr > 50])
print("Even numbers:", arr[arr % 2 == 0])

Greater than 50: [55 72 88 61]
Even numbers: [10 72 20 88]


In [15]:
#Task: Add 5 and 100 to all elements
arr = np.array([1, 2, 3, 4, 5])
print("Add 5:", arr + 5)
print("Add 100:", arr + 100)

Add 5: [ 6  7  8  9 10]
Add 100: [101 102 103 104 105]


In [16]:
#Task: 10 students — total, average, highest, lowest, failed (<35)
marks = np.array([78, 85, 90, 32, 56, 
                  43, 29, 67, 88, 71])

print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Failed students (marks < 35):", marks[marks < 35])

Total: 639
Average: 63.9
Highest: 90
Lowest: 29
Failed students (marks < 35): [32 29]


In [17]:
#Create a multiplication table using NumPy
table = np.arange(1, 11).reshape(10, 1) * np.arange(1, 11)
print(table)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [18]:
#Create a 5×5 matrix from numbers 1 to 25
arr = np.arange(1, 26).reshape(5, 5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [3]:
# Data
import numpy as np
import matplotlib.pyplot as plt
xArray = np.array([50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150])
yArray = np.array([7, 8, 8, 9, 9, 9, 10, 11, 14, 14, 15])

# Create scatter plot
plt.scatter(xArray, yArray)

# Titles and labels
plt.title("House Prices vs. Size")
plt.xlabel("Square Meters")
plt.ylabel("Price in Millions")

# Axis range
plt.xlim(40, 160)
plt.ylim(5, 16)

# Show graph
plt.show()

ModuleNotFoundError: No module named 'matplotlib'