In [3]:
import numpy as np
tc= np.array([[20,85.6,30.2]])
tk = tc * 9/5 + 32
print(tk)
print(tk.ndim)
print(tk.shape)
print(tk.size)
print(tk.dtype)
print(tc.ndim)
print(type(tc))


[[ 68.   186.08  86.36]]
2
(1, 3)
3
float64
2
<class 'numpy.ndarray'>


In [4]:
b= np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(b.ndim)
print(b)

2
[[1 2 3]
 [4 5 6]]


In [5]:
c= np.array([[
    [1, 2, 3],
    [4, 5, 6]],
             
    [[7, 8, 9],
    [10, 11, 12]
    ]])

print(c.ndim)

3


In [8]:
z=np.zeros((3,4))
print(z)

y=np.ones((3,3))
print(y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
n= np.arange(1334,1338)
print(n)    

[1334 1335 1336 1337]


In [ ]:
a=np.ones((3,4))
b=np.zeros((3,4))
result=np.concatenate([a,b])
print(result)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
n=np.eye(3)
print(n)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
n=np.random.rand(3,4)
print(n)

[[0.13810245 0.72457633 0.43746776 0.88950599]
 [0.19449846 0.18639397 0.29625928 0.5226164 ]
 [0.01601208 0.43231132 0.96982582 0.26060094]]


In [17]:
np.random.seed(34)
n=np.random.rand(3,4)
print(n)

[[0.03856168 0.78010046 0.09270376 0.63289269]
 [0.01389085 0.93615854 0.42657438 0.25308645]
 [0.18996531 0.41482463 0.01342061 0.64847278]]


In [19]:
#dot product
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
result=np.dot(a,b)
print(result)


[[19 22]
 [43 50]]


In [20]:
a= np.array([1,2,3,4,5])
b= np.array([6,7,8,9,10])
result=np.dot(a,b)
print(result)

130


In [24]:
a=np.array([[1,2],[3,4]])
b= np.array([[6,7],[8,9]])
result=np.dot(a,b)
print(result)

[[22 25]
 [50 57]]


In [25]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [26]:
#adding axis to the array
arr = np.array([3, 2, 0, 1])
print(arr[np.newaxis, :])   

[[3 2 0 1]]


In [27]:
#slicing
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])  

[2 3 4]


In [28]:
#splitting
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [29]:
#reshaping
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [30]:
#size
arr = np.array([1, 2, 3, 4, 5])
print(arr.size)

5


In [31]:
#searching
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x = np.where(arr == 5)
print(x)

(array([4]),)


In [32]:
#filtering
arr = np.array([41, 42, 43, 44])
x = arr[arr > 42]
print(x)

[43 44]


In [35]:
data =[50,10,20,30,40,23,7,90,54,0.1]
Q1=np.percentile(data,25)
Q2=np.percentile(data,50)
Q3=np.percentile(data,75)
IQR=Q3-Q1
print("Q1:",Q1)
print("Q2:",Q2)
print("Q3:",Q3)
print("IQR:",IQR)

Q1: 12.5
Q2: 26.5
Q3: 47.5
IQR: 35.0
