In [3]:
import numpy as np
tc= np.array([[20,85.6,30.2]])
tk = tc * 9/5 + 32
print(tk)
print(tk.ndim)
print(tk.shape)
print(tk.size)
print(tk.dtype)
print(tc.ndim)
print(type(tc))


[[ 68.   186.08  86.36]]
2
(1, 3)
3
float64
2
<class 'numpy.ndarray'>


In [4]:
b= np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(b.ndim)
print(b)

2
[[1 2 3]
 [4 5 6]]


In [5]:
c= np.array([[
    [1, 2, 3],
    [4, 5, 6]],
             
    [[7, 8, 9],
    [10, 11, 12]
    ]])

print(c.ndim)

3


In [8]:
z=np.zeros((3,4))
print(z)

y=np.ones((3,3))
print(y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
n= np.arange(1334,1338)
print(n)    

[1334 1335 1336 1337]
